# * *****************************************************************
# * POLYTECH-MARSEILLE 2012-2013									*
# * PROGRAMMATION ORIENTEE OBJET									*
# * TP2: LA CLASSE VECTOR											*
# * BALDE THIERNO													*
# *******************************************************************

all : tp4_ex 

tp4_ex : ligne1 ligne2
ligne1: principal.cpp Displayable.cpp  Displayable.h PileGen.h Vector.cpp Vector.h 
ligne2: MesExceptions.h MesExceptions_vector.h MesExceptions_pilegen.h
	g++ -o prog principal.cpp Displayable.cpp Vector.cpp
	
	

